name: Test cross-repo reusable call v2

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  call-echo-proto:
    uses: echo-proto/lz-devtools/.github/workflows/reusable-publish-docker.yaml@main
